kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: o2-benchmark
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # OpenObserve UI
  - containerPort: 30080
    hostPort: 5080
    protocol: TCP
  # OpenSearch API
  - containerPort: 30092
    hostPort: 9200
    protocol: TCP
  # OpenSearch Dashboards (optional)
  - containerPort: 30056
    hostPort: 5601
    protocol: TCP
- role: worker
  extraMounts:
  - hostPath: /tmp/o2-benchmark-data
    containerPath: /data
    readOnly: false
