apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: openobserve
  labels:
    app: openobserve
spec:
  type: NodePort
  selector:
    app: openobserve
  ports:
  - name: http
    port: 5080
    targetPort: 5080
    nodePort: 30080
